name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/dotnet/sdk:8.0

    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v3

    - name: Restore .NET tools
      run: dotnet tool restore

    - name: Build
      run: dotnet build

    - name: Run Integration Tests
      run: dotnet ghul-test --use-dotnet-build integration-tests
